twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
        '%kernel.project_dir%/public/img': images
        '%kernel.project_dir%/public/css': styles
    globals:
        #ressource_directory: '%env(RESSOURCE_PATH)%'
        #ressource_directory: '%kernel.project_dir%/public/Ressource/'
        #uploads_directory: '%kernel.project_dir%/Ressource/'
        uploads_directory: '%env(RESSOURCE_PATH)%'

when@test:
    twig:
        strict_variables: true

when@prod:
    twig:
        auto_reload : true        

