controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

class:
    resource: ../src/Class/
    type: annotation

server:
    resource: ../src/Server/
    type: annotation

error_404:
    path: /error_404
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:    mail/error_404.html.twig

protocol:
    path: /user/protocol
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:    protocol.html.twig

