controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

class:
    resource: ../src/Class/
    type: annotation

server:
    resource: ../src/Server/
    type: annotation