# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
     app.supported_locales: 'en|fr|ko'
     statistics_directory: '%kernel.project_dir%/public/uploads/statistics'
     #uploads_directory: '%kernel.project_dir%/public/Ressource/'
     uploads_directory: '%env(RESSOURCE_PATH)%'
     #uploads_directory: '%kernel.project_dir%/Ressource/'
     packages_directory: '%kernel.project_dir%/src/Ressource/package'
     class_directory: '%kernel.project_dir%/src/Class'
     softwares_directory: '%kernel.project_dir%/public/Ressource/package'
     archives_directory: '%kernel.project_dir%/public/Ressource/archive/package'
    # statistics_directory: '%kernel.project_dir%/public/uploads/statistics'
     #ressource_directory: '%env(RESSOURCE_PATH)%'
     ressource_directory: '%kernel.project_dir%/public/Ressource/'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Services\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'
when@dev:       
    imports:
        #- { resource: '../config.php' }
        #- { resource: '../dataConfig.php' }
        - { resource: '../configServer/*.php' }
when@prod:
    imports:
        - { resource: '../configProd/*.php' }
